name: Android CI
run-name: ${{ github.actor }} testing Android build for GitHub Actions 🚀
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Fail
        run: exit 1

      - name: Send result
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://webhook.site/6c19f3eb-e676-443c-bbce-cfa90120a2c5'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"build": "succsesfull"}'

      #- name: Change wrapper permissions
      #  run: chmod +x ./gradlew

      # Run Tests Build
      #- name: Run gradle tests
      #  run: ./gradlew test

      # Run Build Project
      #- name: Build gradle project
      #  run: ./gradlew build
